handout2:
	sed 's_documentclass\[\]_documentclass[handout]_' 2_seminar.tex > 2_seminar_handout.tex
	pdflatex 2_seminar_handout.tex
	pdflatex 2_seminar_handout.tex
handout3:
	sed 's_documentclass_documentclass[handout]_' 3_seminar.tex > 3_seminar_handout.tex
	pdflatex 3_seminar_handout.tex
	pdflatex 3_seminar_handout.tex


